allowBuilds:
  '"': true
  ',': true
  /: true
  '@': true
  '@heroui/shared-utils': true
  '@swc/core': true
  '[': true
  ']': true
  a: true
  b: true
  c: true
  d: true
  e: true
  esbuild: true
  h: true
  i: true
  l: true
  o: true
  p: true
  r: true
  s: true
  sharp: true
  u: true
  w: true
